# Generated by Django 4.1.4 on 2022-12-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_task_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='link',
        ),
    ]
