# Generated by Django 4.1.4 on 2022-12-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_remove_task_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link',
            field=models.CharField(default='string', max_length=500),
        ),
    ]
